# Generated by Django 3.2.5 on 2021-07-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(default='', max_length=20, null=True)),
                ('link', models.CharField(max_length=200)),
                ('icon', models.CharField(default='', max_length=200, null=True)),
                ('info', models.TextField(default='', null=True)),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
    ]
