# Generated by Django 3.2.5 on 2021-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('time', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
